id: traefik-unauth
info:
  name: Traefik UI Misconfig
  risk: High

params:
  - root: "{{.BaseURL}}"

replicate:
  ports: '8080'
  prefixes: 'traefik,_'

requests:
  - method: GET
    redirect: false
    url: >-
      {{.root}}/api/providers
    headers:
      - User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    detections:
      - >-
        StatusCode() == 200 && StringSearch("resHeader", 'application/json') && StringSearch("response", '{"docker"') && StringSearch("response", 'entryPoints')

references:
  - repo: https://github.com/containous/traefik
